### ISSUE TITLE
neighbours() in scalar context no longer returns the number of neighbours

### ISSUE THREAD

**Issue by merkys** [graphviz-perl/Graph#22]
In v0.9716 and earlier call to
```Perl
scalar $graph->neighbours( $v );
```
used to return the number of neighbours. Starting with v0.9717 `neighbours()` seems to ignore the context of the caller always returning an array. This change might be intentional, as earlier behaviour was not documented. Can you confirm that the current (v0.9717 and later) behaviour is the correct one and will stay?

**Comment by mohawk2** [comment]
This was due to switching to using Set::Object, and returning the result of `$set->members` even in scalar context. Since the behaviour you were expecting is tested and (I think) documented for other, similar methods, I have changed `neighbours` to also match.

Thank you for the report! Released with the fix as 0.9722.

**Comment by merkys** [comment]
Thanks a lot for the fix!
